#!/bin/bash
source cabecalho
mt=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f2)
mf=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f4)
mb=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f6)
ml=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f7)
pp=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F ":" '{print $2}')
csss=$(cat /proc/cpuinfo | grep processor | wc -l)
usoo=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
CPU=$(echo $usoo | awk '{printf("%d\n",$1 + 0.5)}')
##
opti=$(cat < /bin/ejecutar/val)
if [ "$opti" = "0" ]; then
_opti="\033[0;31m [OFF]"
else
_opti="\033[0;31m [\033[0;32mON\033[0;31m]"
fi
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[0;31m [\033[0;32mON\033[0;31m] " || _autorun="\033[0;31m [OFF]"
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
#echo -e "${cor[2]} ‣ \033[1;37m${txt[3]} $_os ${cor[2]}‣ \033[1;37mBase:\033[1;31m$modelo1 ${cor[2]}‣ \033[1;37m${txt[346]}\033[1;31m $_core "
echo -e "\033[1;34m ‣\033[1;31m TOTAL:\033[1;32m "$mt "\033[1;34m ‣ \033[1;31m Libre:\033[1;32m "$ram2 "\033[1;34m ‣ \033[1;31m Usada:\033[1;32m "$ram3
echo -e "\033[1;34m ‣\033[1;31m Uso RAM:\033[1;32m"$_usor "\033[1;34m‣\033[1;31m Uso CPU:\033[1;32m$_usop \033[1;34m ‣\033[1;31m Cache:\033[1;32m"$mb # $CPU"%"
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "${cor[2]} [1] >${cor[3]} ADMINISTRAR USUARIOS "
echo -e "${cor[2]} [2] >${cor[3]} HERRAMIENTAS (\033[0;34mBad/VPN$_badvpn${cor[3]}) (\033[0;34mTCP-SPEED$_tcpspeed${cor[3]})"
echo -e "${cor[2]} [3] >\033[0;33m [!]${cor[3]} OPTIMIZAR VPS "
echo -e "${cor[2]} [4] >\033[0;33m [!]\033[0;31m DESINSTALAR SCRIPT"
#echo -e "${cor[2]} [5] >${cor[3]} ${txt[12]}"
echo -e "${cor[2]} [6] >${cor[3]} Cont/Limit DE USUARIOS $VERIFICAR_PID"
echo -e "${cor[2]} [7] > \e[3;32mHERRAMIENTAS EXTRAS\e[0m \033[0;33m (#EXPERIMENTAL)"
##\033[0;33m [?]\033[1;32m ${txt[341]}\033[0;33m ${txt[342]} "
echo -e "${cor[2]} [8] >${cor[3]} AUTOINICIAR SCRIPT $_autorun"
echo -e "${cor[2]} [9] >${cor[3]} INSTALADOR DE PROTOCOLOS"
#echo -e "${cor[2]} [10] >${cor[3]} Optimizacion Automatica $_opti"
echo -e "${cor[2]} [10] >\033[0;33m [!] \033[0;34mVERIFICAR ACTUALIZACION\033[1;32m"
#echo -e "${cor[2]} [0] >${cor[4]} ${txt[13]}"
echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") "&& msg -bra "\033[1;41m[Regresar / Salir]"
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
#  ceniza
#\033[1;41m rojo
